# Creating materials using MatModel

In [1]:
import pymecht as pmt
import numpy as np

## Single material model

The core module in pyMechT is `MatModel` which allows us to add models together to simulate the stress-strain behavior. A basic usage is when there is only one model, for example we can create a material with Yeoh model, which is isotropic and only a function of the first invariant:

In [2]:
mat1 = pmt.MatModel('yeoh')
print(mat1.parameters) # Returns parameters as a dictionary

------------------------------------------------------------------
Keys              Value       Fixed?      Lower bound Upper bound 
------------------------------------------------------------------
c1_0              1.00        No          1.00e-04    1.00e+02    
c2_0              1.00        No          0.00        1.00e+02    
c3_0              1.00        No          0.00        1.00e+02    
c4_0              0.00        No          0.00        1.00e+02    
------------------------------------------------------------------



In principle, one can directly use this material to calculate stresses given a deformation gradient using `stress` method

In [3]:
mat1.stress?

Signature:
mat1.stress(
    F=array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]),
    theta=None,
    stresstype='cauchy',
    incomp=False,
    Fdiag=False,
)
Docstring:
Returns the stress tensor of the material model

Parameters
----------
F: np.array([3,3])
    the deformation gradient, default: identity matrix (no deformation)

theta: ParamDict or dict
    the parameters of the model, if None, then the default values are used

stresstype: str
    the type of stress tensor to return with the following options (case insensitive) 

        * 'cauchy': Cauchy stress,
        * '1pk' or '1stpk' or 'firstpk': 1st Piola-Kirchoff stress
        * '2pk' or '2ndpk' or 'secondpk': 2nd Piola-Kirchoff stress
        * default: Cauchy stress
    
incomp: bool
    if True, then the material is assumed to be incompressible, default: False
    
Fdiag: bool
    if True, then it is assumed that F is diagonal (for faster computation), default: False

Returns
-------
np.array([3,3])
    th

Thus, we can calculate the Cauchy stress at an identity deformation gradient. However, since this model does not have a volumetric part, we must set incompressibility to be true to get a zero stress. This is done using a Lagrange multiplier, which is calculated internally in pyMechT by setting the normal stress along the third axis equal to zero.

In [4]:
mat1.stress(np.eye(3),incomp=True)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Or, we can calculate other stresses at non-identity deformation gradient

In [5]:
F = np.array([[1.2,0,0],[0.1,1.2,0],[0,0,1]])
print(mat1.stress(F,stresstype='1pk',incomp=True))
print(mat1.stress(F,stresstype='2pk',incomp=True))

[[3.78128667 0.71615278 0.        ]
 [1.03126    3.78128667 0.        ]
 [0.         0.         0.        ]]
[[3.15107222 0.59679398 0.        ]
 [0.59679398 3.10133939 0.        ]
 [0.         0.         0.        ]]


One can also change the parameters and pass them while calculating the stress.

In [6]:
params = mat1.parameters
params['c1_0'].set(2)
print(mat1.stress(F,params,stresstype='1pk',incomp=True))

[[4.51462    0.85504167 0.        ]
 [1.23126    4.51462    0.        ]
 [0.         0.         0.        ]]


Alternatively, instead of passing the parameters, one can set the values and call the `stress` function without the parameters

In [7]:
mat1.parameters = params
print(mat1.stress(F,stresstype='1pk',incomp=True))

[[4.51462    0.85504167 0.        ]
 [1.23126    4.51462    0.        ]
 [0.         0.         0.        ]]


## Adding materials

A convenient feature of pyMechT is that we can easily add different models together (potential same model repeated). For example

In [8]:
mat1 = pmt.MatModel('yeoh','nh')
mat2 = pmt.MatModel('goh','goh','nh')
print(mat1, mat1.parameters)
print(mat2, mat2.parameters)

Material model with 2 components:
Component1: YEOH
Component2: NH
 ------------------------------------------------------------------
Keys              Value       Fixed?      Lower bound Upper bound 
------------------------------------------------------------------
c1_0              1.00        No          1.00e-04    1.00e+02    
c2_0              1.00        No          0.00        1.00e+02    
c3_0              1.00        No          0.00        1.00e+02    
c4_0              0.00        No          0.00        1.00e+02    
mu_1              1.00        No          1.00e-04    1.00e+02    
------------------------------------------------------------------

Material model with 3 components:
Component1: GOH
Component2: GOH
Component3: NH
 ------------------------------------------------------------------
Keys              Value       Fixed?      Lower bound Upper bound 
------------------------------------------------------------------
k1_0              10.00       No          0.10

We can even add them afterwards, although this is rarely needed

In [9]:
mat3 = mat1 + mat2
print(mat3,mat3.parameters)

Material model with 5 components:
Component1: YEOH
Component2: NH
Component3: GOH
Component4: GOH
Component5: NH
 ------------------------------------------------------------------
Keys              Value       Fixed?      Lower bound Upper bound 
------------------------------------------------------------------
c1_0              1.00        No          1.00e-04    1.00e+02    
c2_0              1.00        No          0.00        1.00e+02    
c3_0              1.00        No          0.00        1.00e+02    
c4_0              0.00        No          0.00        1.00e+02    
mu_1              1.00        No          1.00e-04    1.00e+02    
k1_2              10.00       No          0.10        30.00       
k2_2              10.00       No          0.10        30.00       
k3_2              0.10        No          0.00        0.33        
k1_3              10.00       No          0.10        30.00       
k2_3              10.00       No          0.10        30.00       
k3_3           

To get the model components back, we can use the `models` 

In [10]:
mat2.models

(<pymecht.MatModel.GOH at 0x14a61d1c0>,
 <pymecht.MatModel.NH at 0x14a61dd30>)

In [11]:
## Setting fiber directions

Note that, for anisotropic models (such as `goh`), fiber directions need to be specified before they can be called. That is, `mat1` above can be used but not `mat2`

In [12]:
mat1.stress(np.eye(3),incomp=True)
try:
    mat2.stress(np.eye(3),incomp=True)
except ValueError as e:
    print("Value error occured", e)

Value error occured GOH model class uses I4 but no fiber directions have been defined. Did you forget to set the fiber directions?


The fiber directions are set for each component model, and each component can have multiple fiber directions (the response is summed over them). This means, that the individual components can have different fiber directions (which is why one might want to add two GOH models together). Below we set two fiber directions for each of the GOH component.

In [13]:
model_comps = mat2.models
model_comps[0].fiber_dirs = [ np.array([1,1,0]), np.array([0,1,0])]
model_comps[1].fiber_dirs = [ np.array([1,0,0]), np.array([0.5,1,0])]
print(mat2)
print(mat2.stress(np.eye(3),incomp=True))
print(mat2.stress(F,incomp=True))

Material model with 3 components:
Component1: GOH with fiber direction(s):[array([0.70710678, 0.70710678, 0.        ]), array([0., 1., 0.])]
Component2: GOH with fiber direction(s):[array([1., 0., 0.]), array([0.4472136 , 0.89442719, 0.        ])]
Component3: NH

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 84.11760455  66.84260966   0.        ]
 [ 66.84260966 126.67097888   0.        ]
 [  0.           0.           0.        ]]


Note that the fiber direction vectors we supplied were not unit vectors. Internally they are made unit vectors. Thus, when we print them, we see some differences. Lastly, if we also set fiber directions to isotropic materials, it does not affect their response.

In [14]:
model_comps[2].fiber_dirs = [ np.array([1,0,0]), np.array([0.5,1,0])]
print(mat2)
print(mat2.stress(np.eye(3),incomp=True))
print(mat2.stress(F,incomp=True))

Material model with 3 components:
Component1: GOH with fiber direction(s):[array([0.70710678, 0.70710678, 0.        ]), array([0., 1., 0.])]
Component2: GOH with fiber direction(s):[array([1., 0., 0.]), array([0.4472136 , 0.89442719, 0.        ])]
Component3: NH with fiber direction(s):[array([1., 0., 0.]), array([0.4472136 , 0.89442719, 0.        ])]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 84.11760455  66.84260966   0.        ]
 [ 66.84260966 126.67097888   0.        ]
 [  0.           0.           0.        ]]


However, for using pyMechT, one would seldom use the `MatModel` directly. Instead, it would be simply created and then used to create a `SampleExperiment` instance, which internally sets the deformation gradient based on the mode of deformation, incompressibility condition, and even a helper function to set the fiber directions more easily. These aspects are covered in the next examples.